# Generated by Django 4.0 on 2021-12-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
