# Generated by Django 4.0 on 2021-12-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lat', models.CharField(max_length=200)),
                ('long', models.CharField(max_length=200)),
                ('place_id', models.CharField(max_length=255)),
                ('formatted_address', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
