# Generated by Django 4.0 on 2022-01-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_googleaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googleaddress',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='googleaddress',
            old_name='long',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='time',
            new_name='currentTime',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='long',
            new_name='longitude',
        ),
    ]
